;/*FB_PKG_DELIM*/

__d("baseTextWithEntitiesApplyRenderers",["react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react"),j=i.Fragment;function a(a,b,c,d,e,f,g,h,k){var l=a.__typename;h=Object.prototype.hasOwnProperty.call(h,l)?h[l].concat(k):k;return i.jsx(j,{children:h&&h.length>0?h.reduce(function(d,f){return f(d,a,c,e,b)},f):d},g)}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("baseTextWithEntitiesApplyTextTransforms",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){return b!=null?b.reduce(function(a,b){return b(a)},a):a}a.displayName=a.name+" [from "+e.id+"]";f["default"]=a}),66);
__d("baseTextWithEntitiesProcessRange",["UnicodeUtils","baseTextWithEntitiesApplyRenderers","baseTextWithEntitiesApplyTextTransforms","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=h||d("react"),k=j.Fragment;function a(a,b,e,f,g,h,l,m,n,o,p,q){a=(i||(i=d("UnicodeUtils"))).substr(a,b,e-b);e=n.length;a.length>0&&m.push(j.jsx(k,{children:c("baseTextWithEntitiesApplyTextTransforms")(a,o)},"c"+b+"_"+e+"_"+q));o=n.pop();n[n.length-1].subElements.push(c("baseTextWithEntitiesApplyRenderers")(f,g,h,m,a,m,b+"_"+e+"_"+q,l,p));return o}g["default"]=a}),98);
__d("baseTextWithEntitiesSortRanges",[],(function(a,b,c,d,e,f){"use strict";function a(a){return Array.from(a).sort(function(a,b){return a.offset-b.offset||b.length-a.length})}f["default"]=a}),66);
__d("BaseCometTextWithEntitiesBase.react",["UnicodeUtils","baseTextWithEntitiesApplyRenderers","baseTextWithEntitiesApplyTextTransforms","baseTextWithEntitiesProcessRange","baseTextWithEntitiesSortRanges","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=h||d("react"),k=j.Fragment;function a(a){var b,e=a.ranges;e=e===void 0?[]:e;var f=a.renderers,g=a.transforms;g=g===void 0?[]:g;var h=a.text;a=a.disableRangeSort;a=a===void 0?!1:a;f=(f=f)!=null?f:{};var l=0;b=(b=Object.prototype.hasOwnProperty.call(f,"*")?f["*"]:[])!=null?b:[];a=a?e:c("baseTextWithEntitiesSortRanges")(e);e=[{entity:{__typename:""},entity_is_weak_reference:!1,entityType:"",length:h.length,offset:0,subElements:[]}];for(var m=0;m<a.length;++m){var n=a[m],o=n.entity,p=n.entity_is_weak_reference,q=n.entity_type,r=n.length;n=n.offset;if(l>=h.length||n>h.length)break;var s=e[e.length-1],t=s.entity,u=s.entity_is_weak_reference,v=s.entityType,w=s.length,x=s.offset;s=s.subElements;var y=x+w;while(y<=n&&e.length>1){c("baseTextWithEntitiesProcessRange")(h,l,y,t,u,v,f,s,e,g,b,m);l=y;var z=e[e.length-1];t=z.entity;u=z.entity_is_weak_reference;v=z.entityType;w=z.length;x=z.offset;s=z.subElements;y=x+w}l<n&&(e[e.length-1].subElements.push(j.jsx(k,{children:c("baseTextWithEntitiesApplyTextTransforms")((i||(i=d("UnicodeUtils"))).substr(h,l,n-l),g)},"c"+l+"_"+e.length)),l=n);if(x<=n&&y>=n+r){e.push({entity:o,entity_is_weak_reference:(z=p)!=null?z:null,entityType:(y=q)!=null?y:null,length:r,offset:n,subElements:[]})}else{z=(i||(i=d("UnicodeUtils"))).substr(h,n,r);y=c("baseTextWithEntitiesApplyTextTransforms")(z,g);e[e.length-1].subElements.push(c("baseTextWithEntitiesApplyRenderers")(o,(o=p)!=null?o:null,(p=q)!=null?p:null,z,z,y,l+"_"+e.length,f,b));l=n+r}}while(e.length>1){o=e[e.length-1];var t=o.entity,u=o.entity_is_weak_reference,v=o.entityType,w=o.length,x=o.offset;s=o.subElements;q=x+w;c("baseTextWithEntitiesProcessRange")(h,l,q,t,u,v,f,s,e,g,b,e.length);l=q}if(l<h.length){p=e[e.length-1].subElements;p.push(j.jsx(k,{children:c("baseTextWithEntitiesApplyTextTransforms")((i||(i=d("UnicodeUtils"))).substr(h,l),g)},"c"+l))}return j.jsx(j.Fragment,{children:e[e.length-1].subElements})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("Box.react",["react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react"),k={box:{alignItems:"x1qjc9v5",boxSizing:"x9f619",display:"x78zum5",flexBasis:"xdl72j9",flexDirection:"xdt5ytf",flexShrink:"x2lah0s",minHeight:"x2lwn1j",minWidth:"xeuugli",position:"x1n2onr6",zIndex:"x1ja2u2z",$$css:!0}};b=j.forwardRef(a);function a(a,b){a=babelHelpers["extends"]({},a);var d=a.as;d=d===void 0?"div":d;var e=a.xstyle;a=babelHelpers.objectWithoutPropertiesLoose(a,["as","xstyle"]);return j.jsx(d,babelHelpers["extends"]({},a,{className:(h||(h=c("stylex")))(k.box,e),ref:b}))}a.displayName=a.name+" [from "+f.id+"]";e=b;g["default"]=e}),98);
__d("MDSScrollableAreaStyles",[],(function(a,b,c,d,e,f,g){"use strict";a={themed:{scrollbarColor:"x16o0dkt",$$css:!0},unthemed:{scrollbarColor:"xgjnz6y",$$css:!0}};b=a;g["default"]=b}),98);
__d("baseTextWithEntitiesAdjustRanges",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){return a.map(function(a){return babelHelpers["extends"]({},a,{offset:a.offset-b})}).filter(function(a){return a.offset>=0&&a.offset<c})}f["default"]=a}),66);
__d("baseTextWithEntitiesFilterRanges",[],(function(a,b,c,d,e,f){"use strict";function a(a){var b=[];for(var c=0;c<a.length;c++){var d=a[c];if(d!=null&&d.offset!=null&&d.length!=null&&d.entity!=null&&d.entity.__typename!=null){var e;b.push({entity:d.entity,entity_is_weak_reference:(e=d.entity_is_weak_reference)!=null?e:null,length:d.length,offset:d.offset})}}return b}f["default"]=a}),66);
__d("baseTextWithEntitiesSplitRangesAndTextIntoParagraphs",["UnicodeUtils","baseTextWithEntitiesAdjustRanges"],(function(a,b,c,d,e,f,g){"use strict";var h;function i(a){var b=a.ranges;a=a.text;var e=0;return a.split("\n").map(function(a){var f=c("baseTextWithEntitiesAdjustRanges")(b,e,(h||(h=d("UnicodeUtils"))).strlen(a));e+=h.strlen(a)+1;return{ranges:f,text:a}}).filter(function(a){return a.text.trim()!==""})}function a(a,b){var e=a.ranges;a=a.text;var f=0;return a.split(/(?=\n\s*\n)/).map(function(a){var g,j;g=(g=a.match(/(^\n\s*\n)?([^]*$)/))!=null?g:[];j=(j=g[1])!=null?j:"";g=(g=g[2])!=null?g:a;j=c("baseTextWithEntitiesAdjustRanges")(e,f+j.length,(h||(h=d("UnicodeUtils"))).strlen(g));f+=h.strlen(a);return b?i({ranges:j,text:g}):{ranges:j,text:g}})}g["default"]=a}),98);
__d("getTextDirectionAttribute",["cr:1080422"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var c="auto";b("cr:1080422")!=null&&window!=null&&(c=b("cr:1080422").isDirectionRTL(a)?"rtl":"ltr");return c}g["default"]=a}),98);