const KidsImagesData = [{
    image: "https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/design-ideas-thumbnails-1628773921-7vSz1/jfm-2025-1738441429-LLvdg/ai-1738441440-R9rjW/48-1739356753-4x1ki.png",
    details:"Kids Bedroom Design Details:",
    name: "Modern Kids Bedroom Design with Wooden Bed, Study Desk, and Storage",
    style: "Modern",
    rdimensions: "18x20 feet",
    fhighlights: "Single wooden bed with storage, Wooden study table with chair",
    righlights: "Designed for teenagers, this room blends modern aesthetics with smart functionality, offering a cozy sleeping area, efficient workspace, warm lighting, and sleek storage that enhances comfort, productivity, and style in a compact layout.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/design-ideas-thumbnails-1628773921-7vSz1/jfm-2025-1738441429-LLvdg/ai-1738441440-R9rjW/49-1739356751-vXEGi.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Modern Kids Bedroom Design with Bunk Bed and Textured Walls",
    style:"Modern",
    rdimensions:"16x18 feet",
    fhighlights:" The bunk bed is a practical and space-saving solution for children's bedrooms",
    righlights:"The room showcases a practical bunk bed that saves space, making it perfect for a teenager’s growing needs. The textured wallpapered walls add personality and warmth, ensuring the room remains stylish, functional, and ideal for relaxation and creativity.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/1-2025-1736068988-NDPD1/jfm-1736069001-9OxTK/kbr-1736166115-pC7to/kbr-5-1738581078-Wfmkt.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Modern Twins Bedroom Design with Animal Themed Wall Decor",
    style:" Modern",
    rdimensions:"13x12 feet",
    fhighlights:" Two single beds are placed symmetrically with a shared nightstand in between.",
    righlights:" Designed for twins or siblings, this modern bedroom features a symmetrical layout with plush single beds, a stylish shared nightstand, and warm, layered lighting. The neutral color palette and fun decor create a cozy yet sophisticated retreat.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/1-2025-1736068988-NDPD1/jfm-1736069001-9OxTK/kbr-1736166115-pC7to/kbr-4-1738581079-hBYeS.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Scandinavian Kids Bedroom Design with Single Bed and White Chair",
    style:"Scandinavian",
    rdimensions:"7x12 feet",
    fhighlights:"Single bed with grey upholstered headboard. White armless chair with wooden legs.",
    righlights:"This Scandinavian teen bedroom balances functionality and style, featuring a soft grey upholstered bed, a modern wooden study desk, and sleek built-in cabinetry. The neutral color palette and warm lighting create a serene and inviting atmosphere.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/1-2025-1736068988-NDPD1/jfm-1736069001-9OxTK/kbr-1736166115-pC7to/kbr-2-1738581083-pg2T5.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Contemporary Teen Bedroom Design with Blush Pink Pouf and Queen Size Bed",
    style:"Contemporary",
    rdimensions:"16x12 feet",
    fhighlights:"Queen-size bed with an upholstered, tufted headboard in a soft blush pink color.Two floating-style wooden nightstands with a minimal design and a single drawer.",
    righlights:"A sophisticated yet cozy teen bedroom with soft blush tones, modern furniture, and elegant lighting.Warm wood accents, chic decor, and plush textures create a serene and inviting personal sanctuar",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/1-2025-1736068988-NDPD1/jfm-1736069001-9OxTK/kbr-1736166115-pC7to/kbr-1-1738581085-fYdpv.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Twin Kids Contemporary Bedroom Design with Animal Theme",
    style:"Contemporary",
    rdimensions:" 12x12 feet",
    fhighlights:"Two identical beds with curved headboards and a soft beige finish. Two simple nightstands with a clean, modern design, each featuring a single drawer and an open shelf below.",
    righlights:" A beautifully curated twin bedroom with adorable animal murals, soothing colors, and cozy twin beds. Soft lighting, modern furniture, and a playful theme make it an ideal retreat for twins to relax, sleep, and dream.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/design-ideas-thumbnails-1628773921-7vSz1/jfm-2025-1738441429-LLvdg/ai-1738441440-R9rjW/15-1738441730-gXyeE.jpg",
    details:"Kids Bedroom Design Details: ",
    name:"Modern Kids Bedroom Design with Bunk Bed and Soft Pink Walls",
    style:"Modern",
    rdimensions:"20x18 feet",
    fhighlights:" The bunk bed is a practical and space-saving solution for children's bedrooms",
    righlights:" Soft pink vertical-paneled walls add warmth and texture, while cove and chandelier lighting enhance elegance. The practical bunk bed optimizes space, creating a cozy and modern retreat for teenagers",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/2properties-1733457217-X1TuH/photoshoots-1735452784-CzJzx/bangalore-1736150519-Ye8X5/venkat-janga-1736236649-Jx9xO/f013-1736238296-rjuIb.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Contemporary Kids Bedroom Design with Queen Bed and Study Table",
    style:"Contemporary",
    rdimensions:"14x12 feet",
    fhighlights:"Queen size bed with storage, Bay window seating, Study table with chair",
    righlights:"This contemporary teen bedroom features a cozy bay window seat, creating a perfect reading nook, a functional study area for focused learning, and cove lighting that enhances the warm and inviting atmosphere.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/design-ideas-thumbnails-1628773921-7vSz1/jfm-2025-1738441429-LLvdg/ai-1738441440-R9rjW/15-1738441730-gXyeE.jpg",
    details:"Kids Bedroom Design Details: ",
    name:"Modern Kids Bedroom Design with Bunk Bed and Soft Pink Walls",
    style:"Modern",
    rdimensions:"20x18 feet",
    fhighlights:"The bunk bed is a practical and space-saving solution for children's bedrooms",
    righlights:"Soft pink vertical-paneled walls add warmth and texture, while cove and chandelier lighting enhance elegance. The practical bunk bed optimizes space, creating a cozy and modern retreat for teenagers.",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/ond-2024-1727950725-vfT46/kbr-1728897625-2wyz2/ssd-5-1734330942-6Qwxi.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Scandinavian Kids Bedroom Design with Wooden Bed and Study Table",
    style:" Scandinavian",
    rdimensions:"18x14 feet",
    fhighlights:"Wooden bed with study table and wall storage attached.",
    righlights:"Light colour palette of the room adds a spacious and bright feel. Space saving design",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/ond-2024-1727950725-vfT46/kbr-1728897625-2wyz2/kbr-4-1733657415-uTtX6.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Classic Kids Bedroom Design with Queen Bed and Wardrobe",
    style:"Classic",
    rdimensions:"18x16 feet",
    fhighlights:"Queen bed with gery tufted headboard. Guest bedroom with wardrobe and side table",
    righlights:"Bed with storage, wardrobe and side table ideal for kids bedroom",
},
{
    image:"https://images.livspace-cdn.com/w:640/plain/https://d3gq2merok8n5r.cloudfront.net/abhinav/ond-1634120396-Obfdc/1-2025-1736068988-NDPD1/jfm-1736069001-9OxTK/kbr-1736166115-pC7to/kbr-3-1738581081-1er8r.jpg",
    details:"Kids Bedroom Design Details:",
    name:"Blue Elephant-Themed Contemporary Kids Bedroom Design",
    style:"Contemporary",
    rdimensions:"13x12 feet",
    fhighlights:"The centerpiece is a unique upholstered bed with a custom-designed elephant headboard with the bedframe covered in soft blue fabric.",
    righlights:" This charming kids’ room stands out with its playful yet elegant design, featuring a soft upholstered elephant headboard, soothing blue tones, and warm wooden accents.",
}
]

export default KidsImagesData;